### ISSUE TITLE
Añadir el archivo Listas.ipynb a tu repositorio python

### ISSUE THREAD

**Issue by drancope** [Jose-Antonio-21/python#2]
El archivo está en Moodle. Lo tenéis que descargar y se puede subir a vuestro repositorio de dos maneras disitntas, por github o por atom.
a) por github: id a <>Code, y "add file->upload files"
b) por atom: copiar dentro de la carpeta donde esté el proyecto (hay que mirar en el ordenador), y luego "stage", "commit" y "push"

**Comment by Jose-Antonio-21** [comment]
Lo he hecho en Github
