### ISSUE TITLE
Operadores_y_Condicional.ipynb error en ejercicio 9

### ISSUE THREAD

**Issue by drancope** [Jose-Antonio-21/python#8]
No es exactamente un error, pero los resultados son raros: te ofrece una combinación de dos factores para cualquier número que le pones, porque al empezar a contar por 1, siempre encuentra un resultado válido.
Para que haga lo que tiene que hacer, hay que empezar los dos bucles por 2.

**Comment by Jose-Antonio-21** [comment]
Ya lo corregi
